

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: rabbitmq-coreader
      containers:
      - name: rabbitmq
        image: rabbitmq:management  
        ports:
        - containerPort: 5672
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1"
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "admini"


---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{NAMESPACE}}
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672


---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: {{NAMESPACE}}
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672



---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: {{NAMESPACE}}
spec:
  rules:
  - host: rabbitmq.{{PUBLIC_DOMAIN_NAME}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-management
            port:
              number: 15672
